import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { SidebarProvider, SidebarTrigger } from '@/lib/components/ui/sidebar'
import { AppSidebar } from '@/lib/components/app-sidebar'
import { Header } from '@/lib/components/Header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='min-h-screen bg-background text-foreground font-sans antialiased'>
        <div className='flex min-h-screen'>
          {/* Sidebar */}
          <div className='aside'>
            <SidebarProvider>
              <AppSidebar />
              <main>
                <SidebarTrigger />
                {/* {children} */}
              </main>
            </SidebarProvider>
          </div>

          {/* Main content area */}
          <div className='flex-1 border flex flex-col w-full'>
            {/* Header */}
            <div className='w-full'>
              <Header />
            </div>

            {/* Page content */}
            <main className='flex-1 p-6'>{children}</main>
          </div>
        </div>
      </body>
    </html>
  )
}
